server:
  port: 8082
  
app:
  users:
    admin:
      name: Sairandhree
      email: sairandhree@gmail.com
    itUser:
      name: itusername
      email: ituseremail@gmail.com 
      
spring:
   profiles:
     active: dev